name: Build and test

on:
  pull_request:

jobs:

  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Expose git commit data
        uses: rlespinasse/git-commit-data-action@v1.x
      - uses: wagoid/commitlint-github-action@v2
        if: ${{ env.GIT_COMMIT_AUTHOR_NAME != 'dependabot[bot]' }}

  android:
    needs: commitlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: build
        run: ./gradlew :androidApp:buildDebug
      - name: test
        run: ./gradlew test

  ios:
    needs: commitlint
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Kotlin/Native unit tests
        run: ./gradlew iosX64Test
      - name: build and test
        run: xcodebuild test -project iosApp/iosApp.xcodeproj -scheme iosApp -destination "platform=iOS Simulator,name=iPhone 11 Pro"
